### PR TITLE
This package is abandoned, and should be marked as such

### PR DESCRIPTION
**Pull request by BackEndTea**

### CODE REVIEW

**Review by alexions — APPROVED** [review]
Good proposal

**Comment by BackEndTea** [comment]
Thank you @alexions

**Comment by BackEndTea** [comment]
@alexions I'm not seeing this change appear on packagist. Any chance you could update it there as well? My best guess would be that this repo uses the old hook system which i think is no longer supported

**Comment by alexions** [comment]
Thanks for pointing this! Yes, I manually triggered the update. Now package has an abandoned state.

**Pull request merged**
